name: OniGo
main: org.oni.oniGo.OniGo
version: 1.7
commands:
  yasha:
    description: 夜叉効果を開始する
    usage: /yasha
  end:
    description: 夜叉効果を終了する
    usage: /end
  getcmditem:
    description: ゲームアイテムを取得する
    usage: /getcmditem
  re:
    description: プラグインを再起動する
    usage: /re
  start:
    description: 鬼ごっこゲームを開始する（全員のインベントリクリア＋陣営専用アイテム支給）
    usage: /start
  stop:
    description: 鬼ごっこゲームを停止する
    usage: /stop
  select:
    description: 陣営を選択する例 (select player または select oni)
    usage: /select <player/oni>
  onistart:
    description: コマンド実行者を鬼に確定しゲーム開始する
    usage: /onistart
  kisyastart:
    description: コマンド実行者を鬼叉に確定しゲーム開始する
    usage: /kisyastart
  ansyastart:
    description: コマンド実行者を暗叉に確定しゲーム開始する
    usage: /ansyastart
  tukistart:
    description: コマンド実行者を月牙に確定しゲーム開始する
    usage: /tukistart
  set:
    description: チェストやドアなどの条件を登録・変更する
    usage: /set <chest/door> [名前]
  gamegive:
    description: 陣営選択本を全プレイヤーに配布し、ゲームスタート本を特定のプレイヤーに配布する
    usage: /gamegive
  rtp:
    description: 初期スポーン地点にテレポートする(@p @a対応)
    usage: /rtp [プレイヤー名/@p/@a]